SisCad.App/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using SisCad.Application.Interfaces;
using SisCad.Application.Models.Client;
using SisCad.Domain.Interfaces.Notification;
using System;
using System.Threading.Tasks;

namespace SisCad.App.Controllers
{
    public class ClientController : BaseController
    {
        #region Fields

        private readonly IClienteService _clienteService;

        #endregion Fields

        #region Constructors

        public ClientController(INotifier notifier,
            IClienteService clienteService)
            : base(notifier)
        {
            _clienteService = clienteService;
        }

        #endregion Constructors

        #region Methods

        [Route("novo-cliente")]
        public IActionResult Create()
        {
            return View();
        }

        [Route("novo-cliente")]
        [HttpPost]
        public async Task<IActionResult> Create(ClientDataModel request)
        {
            if (ModelState.IsValid is false)
                return View(request);

            await _clienteService.Create(request);

            if (ValidOperation() is false)
                return View(request);

            return RedirectToAction("Index");
        }

        [Route("excluir-cliente/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var client = await _clienteService.Get(id);

            if (ValidOperation() is false)
                return NotFound();

            return View(client);
        }

        [Route("excluir-cliente/{id:guid}")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (ModelState.IsValid is false)
                return View(await _clienteService.Get(id));

            await _clienteService.Delete(id);

            if (ValidOperation() is false)
                return View(await _clienteService.Get(id));

            return RedirectToAction("Index");
        }

        [Route("dados-do-cliente/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var client = await _clienteService.Get(id);

            if (ValidOperation() is false)
                return NotFound();

            return View(client);
        }

        [Route("editar-cliente/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var client = await _clienteService.Get(id);

            if (ValidOperation() is false)
                return NotFound();

            return View(client);
        }

        [Route("editar-cliente/{id:guid}")]
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, ClientDataModel request)
        {
            if (ModelState.IsValid is false)
                return View(request);

            request.Id = id;

            await _clienteService.Update(request);

            if (ValidOperation() is false)
                return View(await _clienteService.Get(id));

            return RedirectToAction("Index");
        }

        [Route("criar-contato/{id:guid}")]
        public ActionResult CreateContact(Guid id)
        {
            return RedirectToAction("Create", "Contact", new {id = id});
        }

        public async Task<IActionResult> Index()
        {
            var clients = await _clienteService.GetAll();

            return View(clients);
        }

        #endregion Methods
    }
}

SisCad.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SisCad.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SisCad.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SisCad.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>